version: "3"

services:
  kutt:
    image: registry.chinaeliteacademy.org/kutt:latest
    depends_on:
      - postgres
      - redis
    command: ["./wait-for-it.sh", "postgres:5432", "--", "npm", "start"]
    ports:
      - "8086:3000"
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_NAME: kutt
      DB_USER: aaronmao
      DB_PASSWORD: Aaronhangzhou1
      REDIS_HOST: redis

  redis:
    image: redis:6.0-alpine
    hostname: 'redis'
    volumes:
      - /mnt/kutt/redis:/data

  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: aaronmao
      POSTGRES_PASSWORD: Aaronhangzhou1
      POSTGRES_DB: kutt
    volumes:
      - /mnt/kutt/psql:/var/lib/postgresql/data
